# Site
title: 'NLBRT's (refuge) Blogsite'
description: 'Yet another place where you can stalk me'
logo: 'assets/images/nlbrt-logo.png'
favicon: 'assets/images/nlbrt-logo.png'
baseurl: '/mundana-theme-jekyll'
email: 'nlbrt@disroot.org'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    nlbrt:
      name:           Nilabrata (NLBRT) Sanyal
      site:           nlbrt.github.io
      avatar:         assets/images/nlbrt-logo.png
      bio:            "I <3 ranting about stuff in life"
      email:          nlbrt@disroot.org
      twitter:        https://twitter.com/imnotnlbrt
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: nlbrt
      avatar: assets/images/nlbrt-logo.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]